language: r
cache: packages
sudo: false
warnings_are_errors: false
r:
  - release
  - devel

r_packages:
- covr

script: 
  - |
    R CMD build .
    travis_wait 20 R CMD check portalcasting*tar.gz

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - libgsl0ldbl
    update: true

after_success:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
