setup_date: '2021-01-20'
setup_R_version:
  platform: x86_64-w64-mingw32
  arch: x86_64
  os: mingw32
  system: x86_64, mingw32
  status: ''
  major: '4'
  minor: '0.3'
  year: '2020'
  month: '10'
  day: '10'
  svn rev: '79318'
  language: R
  version.string: R version 4.0.3 (2020-10-10)
  nickname: Bunny-Wunnies Freak Out
setup_portalcasting_version: 0.20.0
directory_tree:
  main: '.'
  subs:
  - casts
  - models
  - raw
  - data
  - tmp
downloads_versions:
- PortalData-2.65.0
- portalPredictions-2021-01-14

